# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
import pandas as pd
import numpy as np

from snakemake.utils import min_version

min_version("8.24.1")


configfile: "config/config.yaml"


ALL_CIRCLES = lookup(dpath=f"circles", within=config).keys()
ALL_SEGMENTS = [s for c in config["circles"] for s in config["circles"][c]]


wildcard_constraints:
    circle="|".join(ALL_CIRCLES),
    segment="|".join(ALL_SEGMENTS),
    model="|".join(
        [lookup(dpath=f"parameters/nanosim_pretrained_model", within=config), ""]
    ),
    technology="|".join(["nanopore", "illumina"]),


include: "rules/common.smk"
include: "rules/reference.smk"
include: "rules/create_circle_sequences.smk"
include: "rules/simulate_reads.smk"
include: "rules/quality_control.smk"
include: "rules/create_simulated_data_archive.smk"


rule all:
    input:
        final_output(),
