reference:
  # For a quick check of available species, see:
  # https://www.ensembl.org/info/about/species.html
  # For full valid species names, consult the respective table for the release
  # you specify below, for example for ‘112’ this is at:
  # https://ftp.ensembl.org/pub/release-112/species_EnsemblVertebrates.txt
  species: homo_sapiens
  # This build needs to be available for the species and release you selected.
  # One build that is sure to exist is always the one listed in this table:
  # https://ftp.ensembl.org/pub/release-112/species_EnsemblVertebrates.txt
  build: GRCh38
  # Available releases can be checked via:
  # https://ftp.ensembl.org/pub/
  # A recent release is usually recommended, especially for recent builds,
  # as older releases might not contain newer builds.
  release: 112

# PARAMETERS

parameters:
  mean_illumina_joint_read_length: 300
  nanosim_pretrained_model: "human_giab_hg002_sub1M_kitv14_dorado_v3.2.1"
  nanosim_basecaller: "dorado"

# SAMPLE SETUP

# Each group has an a1 and an a2 alias sample, which can contain different
# circles at different coverages. The coverage value per circle that is listed
# here is the intended Illumina coverage. The simulation will aim for a
# Nanopore coverage of about 1/4 of that, but will usually end up with a
# slighlty lower coverage due to the effects described here:
# https://github.com/bcgsc/NanoSim/issues/241#issue-2828154586
groups:
  g01:
    a1:
      c03: 60
      c01: 40
    a2:
      c03: 76
  g02:
    a1:
      c03: 80
      c04: 40
      c02: 40
    a2:
      c03: 132
      c04: 36
  g03:
    a1:
      c03: 72
    a2:
      c03: 68
      c05: 32
  g04:
    a1:
      c02: 32
      c03: 320
    a2:
      c03: 124
      c04: 28
  g05:
    a1:
      c02: 280
    a2:
      c03: 40
  

# For each circle, you can define one or more segments on chromosomes from the
# genome version you specify above. Sequence segments will be concatenated in
# the order given, taking the sequence from the specified strand. Segment names
# can be chosen arbitrarily and are mainly for tracking in quality control and
# in validating results.
circles:
  # circle 01
  c01:
    # segment 01_01 (circle 01, segment 01)
    s01_01:
      chrom: 19
      start: 58294322
      end: 58322404
      name: ERVK3-1
      strand: "+"
    s01_02:
      chrom: 21
      start: 6205065
      end: 6228319
      name: Y_RNA
      strand: "-"
  c02:
    s02_01:
      chrom: 21
      start: 21147004
      end: 21166108
      name: NCAM2_fragment
      strand: "+"
    s02_02:
      chrom: 21
      start: 20996019
      end: 21015007
      name: NCAM2_start
      strand: "+"
  c03:
    s03_01:
      chrom: 19
      start: 11364421
      end: 11395197
      name: EPOR
      strand: "-"
  c04:
    s04_01:
      chrom: 21
      start: 39851347
      end: 39879021
      name: PCP4_start 
      strand: "+"
  c05:
    s05_01:
      chrom: 19
      start: 38253526
      end: 38346624
      name: PPP1R14A
      strand: "-"